### ISSUE TITLE
Where is the pretrain_DMSM.py , please next time if you want to share a code , share it all , cause there many problems we face in your code , luck of data ! 

### ISSUE THREAD

**Issue by OuissalTAIM** [hiarsal/DAE-GAN#3]

**Comment by hiarsal** [comment]
Sorry for the confusion and thanks for your kind and professional reminder, I have uploaded the pretrained model through available Google Drive compared with previous Baidu link.
We also adopted the pretrained DAMSMencoders from AttnGAN, since they share the same datasets (e.g., CUB and COCO). For convenience, we provide two links for pretrained DAMSMencoders from AttnGAN.
